### ISSUE TITLE
I'm sorry, the addition of static weather has failed.

### ISSUE THREAD

**Issue by kickTiger** [willasm/obsidian-open-weather#12]
I should have added the static weather according to the style in the example. Here are the steps I followed:
1. I created a new template file under the template folder specified by the Templater plugin and called it.
2. The journal file called the template file. All other Templater syntax is generated correctly, except for the static weather which cannot be generated.
I am not sure whether I need to set up the Templater or Banner plugin specially.

I used the syntax from EXAMPLE.md directly in my template, and I also tried calling `%weather1%` alone, but it didn't work.
```js
---
cssclass: daily
banner: "https://www.bing.com/th?id=OHR.AdelieWPD_EN-US5175747404_1920x1080.jpg&w=1920"
banner_x: 0.0954
banner_y: 0.48572
title: 000 homepage
created: 2023-04-25
author: coffee
banner_icon: 📅 
type: journal
webclip: false
tags: [daily_note]
aliases: []
description: Daily Note
obsidianEditingMode: live
---
%weather3%

<div class="weather_historical_3">%weather3%</div>
<div class="weather_current_4"></div>
<%* app.commands.executeCommandById("obsidian-open-weather:replace-template-string")%>
```
The displayed effect is as shown in the picture, and %weather3% was not recognized correctly.
![image](https://user-images.githubusercontent.com/3623068/234302065-2729a633-019a-4e7a-92f0-484d50179c96.png)

**Comment by willasm** [comment]
What do you have in the `daily.css` file? It is partially working for me.
The <%* app.commands.executeCommandById("obsidian-open-weather:replace-template-string")%> should not be required, I have to check the documentation on that.
The weather information below the image is produced from the `%weather3%` you have right below the yaml which is probably not what you want..

![Daily](https://user-images.githubusercontent.com/94352899/234367330-2d1c5d18-d4ee-4624-a764-f4d2a523b11e.jpg)

**Comment by willasm** [comment]
Can you try using this css and let me know how it looks.

```css
/*====================*/
/* Daily Note Styling */
/*====================*/
.daily {
    padding-left: 25px !important;
    padding-right: 25px !important;
    padding-top: 20px !important;
}

/* Transition Effect Weather One */
.weather_current_1,
.weather_historical_1 {
  transition: 0.3s;
}

/* Transition Effect Weather Two */
.weather_current_2,
.weather_historical_2 {
  transition: 0.3s;
}

/* Transition Effect Weather Three */
.weather_current_3,
.weather_historical_3 {
  transition: 0.3s;
}

/* Transition Effect Weather Four */
.weather_current_4,
.weather_historical_4 {
  transition: 0.3s;
}

/* Historical & Current weather One, Two, Three and Four common settings */
.weather_historical_1, .weather_current_1, .weather_historical_2, .weather_current_2, .weather_historical_3, .weather_current_3, .weather_historical_4, .weather_current_4 {
    display: flex;
    float: left;
    clear: left;
    align-items: center;
    top: 80px;
    left: 35px;
    position: absolute;
    font-family: monospace;
    font-size: 14pt !important;
    margin: 10px 5px;
    padding: 10px 20px;
    border-radius: 20px;
    box-shadow: 3px 3px 2px #414654;
    cursor: pointer;
}

/* Historical weather at top of the document over banner */
.weather_historical_1, .weather_historical_2, .weather_historical_3, .weather_historical_4 {
    color: #d0dce9;
    background-color: #0d3d56;
}

/* Current weather at top of the document over banner */
.weather_current_1, .weather_current_2, .weather_current_3, .weather_current_4 {
    color: #c4caa5;
    background-color: #133e2c;
    opacity: 0;
}

/* Show Current weather One on hover */
.weather_current_1:hover {
    opacity: 1;
}

/* Show Current weather Two on hover */
.weather_current_2:hover {
    opacity: 1;
}

/* Show Current weather Three on hover */
.weather_current_3:hover {
    opacity: 1;
}

/* Show Current weather Four on hover */
.weather_current_4:hover {
    opacity: 1;
}

/* Daily Note Name H6 Styling (YYYY-MM-DD) */
.daily h6 {
    font-size: 1.75em;
    color: #4cbf90;
    border-width: 1px;
    padding-bottom: 3px;
    text-align: center;
}

/* Daily Note Date H5 Styling (🔹 Thursday 🔹 10th November 🔹 2022 🔹) */
.daily h5 {
    font-size: 1.25em;
    color: #23a49d;
    border-width: 1px;
    padding-bottom: 3px;
    text-align: center;
}

/* Hide the frontmatter for Daily Notes */
.daily .frontmatter-container {
    display: none;
}
```
