### ISSUE TITLE
dynamically updating weather in a dashboard

### ISSUE THREAD

**Issue by barnabaslabs** [willasm/obsidian-open-weather#3]
Hello, 
I use a page that I call my "Daily Dashboard" to pull in a variety of data and tasks. The content is static relying on embeds and queries to pull in current information. I'm trying to use your plugin to add the weather to this page, but so far I've been unsuccessful. I can add it using a command, but this doesn't update. I tried using `<div class="weather_current_1"></div>` but nothing displays. Am I doing it wrong or is this possible? I need it refresh without depending on a daily template loading. 
Thanks!
Jack

**Comment by willasm** [comment]
This is very strange? I was able to reproduce this once but restarted Obsidian and I can not get it to happen again?
Try restarting Obsidian and let me know if it is working after that. 

For dynamic weather you do need to use the div like `<div class="weather_current_4"></div>` and use "weather_current_1", "weather_current_2", "weather_current_3" or "weather_current_4" inside the div to correspond to one of the four strings in the settings.

Also, are you seeing any errors? If you just got your API key it will be a while before it is activated.

**Comment by barnabaslabs** [comment]
![image](https://user-images.githubusercontent.com/121033/211425086-a82c32cd-7157-48c7-84ca-45f957208947.png)

I opened the developer console, but there are no errors. The weather does show correctly in the status bar, and I can insert it using the command palette. I tried disabling every plugin except yours then restarting, but still nothing in live preview or reading mode.

**Comment by willasm** [comment]
This is frustrating!!! I got it to happen one more time and switching to another note and back fixed it? I thought it might have to do with the update frequency time setting in the plugin settings (default is 15 min) but that is not it. It should update automatically when switching to edit or preview mode which it does for me 99% of the time. I'm going to check my code for the triggers to update the div. Maybe something changed with the last big update to Obsidian. I also will point out I have only been using them in my daily notes template which works every time. I have only been able to reproduce this by manually adding the div to a note. I'll keep at it until I find the problem.

One of the triggers is on file open, so try closing the note and open it again and see if that triggers it.

**Comment by willasm** [comment]
May be getting somewhere with this. I got it to happen again and checked it out in the dev console and the div is actually updated with the current weather, it is just not being displayed. the opacity is set to zero for some reason which I have it set to in my daily template to create the hover effect, but this is happening with that css snippet disabled? I'm close to figuring this out.

You may want to try using `<div class="weather_current_1" style="opacity: 1;"></div>` to force opacity to 1.

**Comment by willasm** [comment]
Finally solved this! It requires a css snippet to be added to your snippets folder. I'm not sure why as it should still display the weather string, just without any styling. That was how it was working originally. Anyhow to enable this, first add to the frontmatter of the note your using it in the following cssclass line...

```
---
cssclass: openweather
---
```

Then add the following css snippet to your vaults snippet folder `vault/.obsidian/snippets` (create the snippets folder if it does not exist already)...
Don't forget to enable the snippet in settings/appearance (at the bottom).

```css
.openweather {
    padding-left: 25px !important;
    padding-right: 25px !important;
    padding-top: 20px !important;
}

/* Current weather One, Two, Three and Four settings */
/* These are not necessary but demonstrate how to style the weather string */
.weather_current_1, .weather_current_2, .weather_current_3, .weather_current_4 {
    display: flex;
    float: left;
    clear: left;
    color: #c4caa5;
    background-color: #133e2c;
    align-items: center;
    top: 80px;
    left: 35px;
    position: absolute;
    font-family: monospace;
    font-size: 14pt !important;
    margin: 10px 5px;
    padding: 10px 20px;
    box-shadow: 3px 3px 2px #414654;
}
```

Thanks for bringing this to my attention. I will update the readme to reflect this information.
